### ISSUE TITLE
Read Existing Project References

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/ML-Mentorship-GovSchool#3]
Description: The best advice I can give you for selecting project topics is to look at examples that myself and others have contributed to. Attached to this issue will be several videos and documents that I would like you both to explore to gather more insight into the possibilities for the project. 

Acceptance Criteria: Use this issue to assist with #2 

Gavin's GitHub Projects:
Protein Interaction Classification via Rapid Miner - https://github.com/gavinjalberghini/Protein-Interaction-Classifier
Unity/Android Mobile Game to Teach Basic Java - https://github.com/gavinjalberghini/Hack-Heist
Local Projects (Not on GitHub) - https://drive.google.com/file/d/1PiaGd6cS81CXansEnTOh-vcv6wa5sAsz/view?usp=sharing

Community Projects:
Nvidia Jetson Community Projects - https://developer.nvidia.com/embedded/community/jetson-projects
Unity ML Agents - https://unity.com/products/machine-learning-agents

**Comment by gavinjalberghini** [comment]
V: 1

**Comment by JasonDCox** [comment]
Completed - Jason

**Comment by brandonC1234** [comment]
Completed - Brandon
