### ISSUE TITLE
Configure Python Enviornment on Ubuntu

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/ML-Mentorship-GovSchool#6]
Description: We need to get more familiar with Linux and Ubuntu. For this task, we will install Python onto our VMs. Once Python is successfully configured, we will validate by running a Python program. You can install Python via the methods below, or you can run "sudo apt-get update && sudo apt-get upgrade" which will refresh your package manager and provide a default installation of Python. 

Acceptance Criteria: Run any Python script on your virtual machine. 

Python Hello World - https://www.learnpython.org/en/Hello%2C_World%21
Install Python3 on Ubuntu - https://phoenixnap.com/kb/how-to-install-python-3-ubuntu
Pycharm installation - https://www.jetbrains.com/pycharm/download/#section=windows

**Comment by gavinjalberghini** [comment]
V: 1

**Comment by JasonDCox** [comment]
Completed - Jason

**Comment by brandonC1234** [comment]
Decided to go with anaconda.

Completed - Brandon
