### ISSUE TITLE
Understand Different Types of Classification Tasks

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/ML-Mentorship-GovSchool#8]
Description: Throughout the year we will focus on classification tasks for Machine Learning. It is important to understand the types of problems that classifiers can solve. Read the following documentation and references to achieve a better understanding of classification tasks. 

Acceptance Criteria: Be prepared to discuss how the kNN algorithm is used to solve classification problems at the next meeting. 

Types of Classification Tasks - https://machinelearningmastery.com/types-of-classification-in-machine-learning/
8 Classifier Algorithms - https://data-flair.training/blogs/machine-learning-classification-algorithms/

**Comment by gavinjalberghini** [comment]
V: 1

**Comment by JasonDCox** [comment]
Completed - Jason

**Comment by brandonC1234** [comment]
Completed - Brandon
